strategy:
  rollingUpdate:
    maxSurge: 20
    maxUnavailable: 100%
  type: RollingUpdate

podAnnotations:
  "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"

nodeSelector: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

terminationGracePeriodSeconds: 300

image:
  repository: ghcr.io/alephdata/ingest-file
  tag: "3.11.2"
  pullPolicy: Always

containerSecurityContext:
  readOnlyRootFilesystem: true

containerResources:
  requests:
    cpu: 300m
    memory: 2000Mi
  limits:
    # cpu: 1000m
    memory: 3000Mi

env:
  WORKER_THREADS: 0
  OCR_VISION_API: false
  INGESTORS_CONVERT_DOCUMENT_URL: http://aleph-convert-document.default.svc.cluster.local:3000/convert

# Scaling - templates/hpa.yaml

hpa:
  minReplicas: 5
  maxReplicas: 60
  scalingMetrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 100
