apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.global.namingPrefix }}-convert-document-policy
  # namespace: {{.Values.global.namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.global.namingPrefix }}-convert-document
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.global.namingPrefix }}-ingest-file
      ports:
        - protocol: TCP
          port: 3000