apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: convert-document-policy
  # namespace: {{.Values.global.namespace}}
spec:
  podSelector:
    matchLabels:
      app: convert-document
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: search-ingest-file
      ports:
        - protocol: TCP
          port: 3000