apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.global.namingPrefix }}-ingress-staging
  namespace: staging
spec:
  rules:
    - host: aleph.staging
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.global.namingPrefix }}-ui
              servicePort: 80
          - path: /api
            backend:
              serviceName: {{ .Values.global.namingPrefix }}-api
              servicePort: 8000
