apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.namingPrefix }}-ui
  # namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.namingPrefix }}-ui
spec:
  type: NodePort
  selector:
    app: {{ .Values.global.namingPrefix }}-ui
  ports:
    - port: 80
      targetPort: 80
      name: http
