strategy:
  rollingUpdate:
    maxSurge: 2
    maxUnavailable: 100%
  type: RollingUpdate

podAnnotations: {}

nodeSelector: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

image: {}

# Scaling:
replicas: 2

containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

containerResources:
  requests:
    cpu: 301m
    memory: 300Mi
  limits:
    # cpu: 1000m
    memory: 800Mi

env:
  WORKER_THREADS: 5
