apiVersion: apps/v1
kind: Deployment
metadata:
  name: aleph-api
  # namespace: {{ .Values.global.namespace }}
  labels:
    app: aleph-api
spec:
  selector:
    matchLabels:
      app: aleph-api
  strategy: {{- toYaml .Values.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        app: aleph-api
      annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      restartPolicy: Always
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - gunicorn
            - "--timeout"
            - "3600"
            - "--keep-alive"
            - "60"
            - "--threads"
            - "10"
            # - '--worker-class'
            # - 'eventlet'
            - "--bind"
            - 0.0.0.0:8000
            - --log-level
            - debug
            - --log-file
            - "-"
            - --access-logfile
            - "-"
            - aleph.wsgi:app
          volumeMounts:
            {{ if .Values.global.google }}
            - mountPath: /var/secrets/google
              name: aleph-api-service-account
              readOnly: true
            {{ end }}
            - mountPath: /tmp
              name: tmp-volume
            - mountPath: /home/app
              name: home-volume
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.containerResources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.global.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}  
            {{- range $key, $value := .Values.global.secretenv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}  
          readinessProbe:
            httpGet:
              path: /healthz?ready
              port: 8000
            initialDelaySeconds: 5
            # timeoutSeconds: 5
            # periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz?live
              port: 8000
            initialDelaySeconds: 5
            # timeoutSeconds: 5
            # periodSeconds: 20
            # failureThreshold: 10
      volumes:
        {{ if .Values.global.google }}
        - name: aleph-api-service-account
          secret:
            secretName: aleph-api-service-account
        {{ end }}
        - name: tmp-volume
          emptyDir: {}
        - name: home-volume
          emptyDir: {}
