apiVersion: batch/v1
kind: Job
metadata:
  name: aleph-upgrade
  # namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    # "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 60
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: aleph-upgrade
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      restartPolicy: Never
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: aleph-upgrade
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["aleph", "upgrade"]
          volumeMounts:
            {{ if .Values.global.google }}
            - mountPath: /var/secrets/google
              name: aleph-api-service-account
              readOnly: true
            {{ end }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.upgrade.containerResources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.global.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}  
            {{- range $key, $value := .Values.global.secretenv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }} 
      volumes:
        {{ if .Values.global.google }}
        - name: aleph-api-service-account
          secret:
            secretName: aleph-api-service-account
        {{ end }}