strategy:
  rollingUpdate:
    maxSurge: 4
    maxUnavailable: 10%
  type: RollingUpdate

podAnnotations: {}

nodeSelector:
  tier: application

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

image:
  pullPolicy: Always

containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

containerResources:
  requests:
    memory: 2000Mi
    cpu: 200m
  limits:
    memory: 3000Mi

env:
  # Needs google credentials only to access Google Storage and Vision API
  # GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/google/service-account.json

# Scaling - templates/hpa.yaml

hpa:
  minReplicas: 1
  maxReplicas: 14
  scalingMetrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60

# Aleph Upgrade Job - templates/upgrade.yaml

upgrade:
  containerResources:
    requests:
      memory: 600Mi
