apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.namingPrefix }}-convert-document
  labels:
    app: {{ .Values.global.namingPrefix }}-convert-document
spec:
  selector:
    app: {{ .Values.global.namingPrefix }}-convert-document
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      protocol: "TCP"
      name: api
