apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.namingPrefix }}-api
  # namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.namingPrefix }}-api
spec:
  selector:
    app: {{ .Values.global.namingPrefix }}-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: "TCP"
      name: api
